services:
  app:
    image: mysociety/parl_register_experiment:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/workspaces/parl_register_experiment/