services:
  app:
    image: mysociety/parl_register_interests:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /workspaces/parl_register_interests
    volumes:
      - ./:/workspaces/parl_register_interests/
